name: flutter_application
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  intl: any
  smooth_page_indicator: ^1.2.0+3
  flutter_localization: ^0.2.3
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_storage: ^12.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
